marticliment/UniGetUI

- readme.md
This is my version of the readme - feel free to use it.
> readme.md: Improve typography/grammar

- readme.md
Noticed that it was very tight between the screenshots. This should be more aesthetically pleasing as well as easier to view.
> readme.md: Adding space between screenshots

- readme.md
Adds installation instructions for Scoop
> readme.md: Add installation instructions for Scoop

- wingetui/storeEngine.py
fixed the typo "lanuch" in the About section of Winget
> fixed typo in the About section

- readme.md
FAQ is at page bottom and wiki is referenced below installation
> Create wiki + add FAQ

- WingetUI.iss
> Improve installer order

- wingetui/uiSections.py
Capitalize a few things; add space between WingetUI Settings and General preferences; replace "Origin" and "Installation source" simply with "Source"; Project Homepage with just Homepage; and update project description.
> Capitalize section titles + few more things

- wingetui/uiSections.py
> Improve menu options

- wingetui/uiSections.py
Oops. Yesterday I changed the wrong line in https://github.com/martinet101/WingetUI/pull/293
> small context menu inconsistency 2nd attempt

- .github/ISSUE_TEMPLATE/feature-request--add-new-abilities-functions-etc--.md
This difference between bugs and features wasn't intentional, right?
> assign 'martinet101' like for bugs

- .github/ISSUE_TEMPLATE/bug-report--something-is-not-working-as-expected-.md
use <details> to make possiple to hide it
> Log hinders page navigation

- wingetui/uiSections.py
* b69ccd2ac1b8f9e31e15d84e62102b34d59ecd40
> Revert reverted changes from b69ccd2

- wingetui/__init__.py
- wingetui/uiSections.py
> panther7 suggestion + rename Available Updates to Software Updates

- wingetui/__init__.py
Fix #527 
Maybe need more improvements for other langauges.
> Use PySide translations for native elements

- wingetui/storeEngine.py
> fix: properly update packages: use winget update command

- WingetUI.iss
-----
I don't think it works for scoop. See https://github.com/marticliment/WingetUI/issues/601
Is this a problem?
-----
Closes #XXXX
Relates to https://github.com/marticliment/WingetUI/discussions/452
> Fix unable to uninstall WingetUI while running

- wingetui/scoopHelpers.py
> finish fixing #474

- scripts/download_translations.py
- wingetui/uiSections.py
> Improvements

- wingetui/resources/uninstall_scoop.cmd
-----
-----
and how to auto select none or Disable scoop aftar uninstall scoop?
> WingetUI will be restarted to continue for remove scoop from your machine.

- readme.md
> remove from FAQ question about Chocolatey availability

- readme.md
> fix typos / scoop install on readme

- .github/ISSUE_TEMPLATE/bug-report--something-is-not-working-as-expected-.md
- .github/ISSUE_TEMPLATE/feature-request--add-new-abilities-functions-etc-.md
- .github/ISSUE_TEMPLATE/issue-related-to-the-chocolatey-package-manager.md
- .github/ISSUE_TEMPLATE/report-related-to-the-scoop-package-manager.md
- .github/ISSUE_TEMPLATE/winget--issue-or-feature-request-related-to-winget-.md
> fixFaqLink

- wingetui/uiSections.py
-----
-----
Closes #XXXX
Relates to https://github.com/marticliment/WingetUI/issues/893#issuecomment-1501661744
> fix 'not' missing

- wingetui/scoopHelpers.py
> fix scoop package not self-elevating

- wingetui/__init__.py
- wingetui/mainWindow.py
- wingetui/storeEngine.py
- wingetui/uiSections.py
> Fixed translation strings

- scripts/create_translations.py
- scripts/download_translations.py
- scripts/tolgee_requests.py
- scripts/translation_utils.py
Usage:
```sh
python scripts/create_translations.py -h
python scripts/create_translations.py --online
python scripts/create_translations.py -p
python scripts/create_translations.py --print-all > not_translated.json
```
@marticliment
> Added script for upload new translation strings

- scripts/create_translations.py
- scripts/translation_utils.py
More universal "fix": https://github.com/marticliment/WingetUI/commit/c3a28eec903f0242c0728880d2c729a00e6db221
> Update translation utils

- scripts/create_translations.py
- scripts/tolgee_requests.py
- scripts/translation_commands.py
Rename to `translation_commands.py`
New command argument `-d`
Usage:
```
// Delete not trasnlated strings with confirm via Tolgee API (online)
python scripts/create_translations.py -d -m --online
```
> Improve translation utils

- requirements.txt
- wingetui/customWidgets.py
- wingetui/genericCustomWidgets.py
- wingetui/mainWindow.py
- wingetui/scoopHelpers.py
- wingetui/storeEngine.py
- wingetui/tools.py
- wingetui/uiSections.py
- wingetui/wingetHelpers.py
Add modern notification support, inclusing action buttons:
Closes #646 
Closes #680
> Modern notifications

- wingetui/storeEngine.py
**Notes is still not present in Tolgee**
Closes https://github.com/marticliment/WingetUI/issues/955
> Rename 'release notes' to just 'notes' (scoop)

- readme.md
> remove ms store unavailable from FAQ

- .github/ISSUE_TEMPLATE/bug-issue.yml
> New issues

- wingetui/PackageManagers/PackageClasses.py
- wingetui/PackageManagers/choco.py
- wingetui/PackageManagers/npm.py
- wingetui/PackageManagers/pip.py
- wingetui/PackageManagers/sampleHelper.py
- wingetui/PackageManagers/scoop.py
- wingetui/PackageManagers/winget.py
- wingetui/__init__.py
- wingetui/customWidgets.py
- wingetui/genericCustomWidgets.py
- wingetui/mainWindow.py
- wingetui/storeEngine.py
- wingetui/tools.py
- wingetui/uiSections.py
Do not require an app restart to re-apply a theme
fix #1249
> Automatically change theme when system theme changes

- wingetui/PackageManagers/winget.py
> fix Steam and Uplay

- wingetui/PackageEngine/Managers/powershell.py
-----
skip updateSources() for powershell gallery to fix https://github.com/marticliment/WingetUI/issues/1655
-----
Closes #1655
> Update powershell updateSources()

- wingetui/Core/Languages/LangData.py
-----
Code changes: See diff, can't really explain it any better that the diff does
> Add Norwegian nynorsk and Finnish to language data

- src/wingetui/App.xaml.cs
- Extracted error handling into `RegisterErrorHandling` private method.
- Abstracted WebView user data folder setup to `SetUpWebViewUserDataFolder` private method.
- Moved main window initialization code into `InitializeMainWindow` private method.
- Extracted the notification history clearance code into `ClearNotificationHistory` private method.
- Encapsulated notification event registration into `RegisterNotificationActivationEvent` private method.
- Used `ConfigureAwait(false)` for non-awaiting background tasks to improve efficiency.
- Replaced individual package manager initialization with `List<T>.AddRange` for batch addition.
- Implemented `Task.WhenAll` with a timeout using `Task.WaitAsync` to parallelize package manager initialization.
- Used private methods to reduce code …
> Refactor MainApp for Async Efficiency

- readme.md
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing and testing code that does not even compile, breaks other features or does not introduce any useful changes. Thank you for your understanding
-----
No need to declare redundant `extra` after adding the bucket.
-----
> Update installation step via Scoop

- .github/ISSUE_TEMPLATE/bug-issue.yml
- .github/ISSUE_TEMPLATE/hard-crash.yml
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding
-----
Correcting spelling mistakes.
-----
> Update bug-issue.yml and hard-crash.yml to Correct spelling mistakes

- readme.md
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding
> Add Missing Line Break in CLI Parameters Section of README

- src/UniGetUI/Interface/MainView.xaml.cs
- src/UniGetUI/Interface/Pages/IPageWithKeyboardShortcuts.cs
- src/UniGetUI/Interface/Pages/LogPage.xaml.cs
- src/UniGetUI/Interface/SoftwarePages/AbstractPackagesPage.xaml.cs
- src/UniGetUI/Interface/SoftwarePages/PackageBundle.xaml.cs
- src/UniGetUI/UniGetUI.csproj
QoL improvements to keyboard navigation
> Keyboard navigation

- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.
> Fix typo "Naive" -> "Native"

- .github/ISSUE_TEMPLATE/bug-issue.yml
- .github/ISSUE_TEMPLATE/enhancement-improvement.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
Update Issue and Pull Request templates.
-----
> Update Issue and Pull Request templates

- README.md
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
As the package was renamed in winget the documented install comand did not work anymore.
I've changed it to the package identifier as this should be more stable.
> update installation via winget in ReadMe

- src/UniGetUI.PackageEngine.Managers.PowerShell7/PowerShell7.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/PowerShell7SourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/UniGetUI.PackageEngine.Managers.PowerShell7.csproj
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.PackageEngine/PEInterface.cs
- src/UniGetUI.PackageEngine.PackageEngine/UniGetUI.PackageEngine.PEInterface.csproj
- src/UniGetUI.sln
- src/UniGetUI/Interface/Pages/SettingsPage.xaml.cs
Add support for PowerShell 7
fix #1994
fix #1650
fix #2466 
fix #2504
> Add PowerShell 7.x Support

- src/UniGetUI.PackageEngine.Managers.Chocolatey/Chocolatey.cs
Changed Chocolatey description to the one which used in Tolgee/all location files.
> Fix translation line for Chocolatey

- src/UniGetUI.PackageEngine.Package/Package.cs
Constuct -> Construct
-----
-----
Closes #XXXX
> chore: update Package.cs

- src/UniGetUI.PAckageEngine.Interfaces/ManagerProviders/IPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Chocolatey/Providers/ChocolateyDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Dotnet/DotNet.cs
- src/UniGetUI.PackageEngine.Managers.Dotnet/Providers/DotNetDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Generic.NuGet/BaseNuGet.cs
- src/UniGetUI.PackageEngine.Managers.Generic.NuGet/BaseNuGetDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Npm/Providers/NpmPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Pip/Providers/PipPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell/PowerShell.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell/Providers/PowerShellDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/PowerShell7.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/Providers/PowerShell7DetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Providers/ScoopPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/Providers/WinGetPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/BaseProviders/BasePackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/Classes/NullPackageManager.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/PackageManager.cs
- src/UniGetUI/Interface/SoftwarePages/AbstractPackagesPage.xaml.cs
- src/UniGetUI/Interface/SoftwarePages/InstalledPackagesPage.cs
- src/UniGetUI/Interface/SoftwarePages/SoftwareUpdatesPage.cs
Add an option to open the install location of a package.
fix #2489
fix #2260
fix #1386
fix #959
> Open package install location

- src/UniGetUI.Core.Tools.Tests/ToolsTests.cs
- src/UniGetUI.Core.Tools/Tools.cs
- src/UniGetUI/Interface/SoftwarePages/AbstractPackagesPage.xaml.cs
Fix some packages not showing unless the page gets force-refreshed.
This does NOT fix the issue where the page doesn't render.
fix #2627
fix #2635
fix #2391
> Fix certain packages not showing on software pages

- README.md
-----
For the old command I get a message that the packge was not found.
-----
Closes #XXXX
> Update Winget package id

- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Classes/PackageWrapper.cs
- src/UniGetUI/MainWindow.xaml
- src/UniGetUI/MainWindow.xaml.cs
- src/UniGetUI/Pages/DialogPages/DialogHelper_Generic.cs
- src/UniGetUI/Pages/SettingsPage.xaml.cs
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs
- src/UniGetUI/Pages/SoftwarePages/InstalledPackagesPage.cs
Add an automated WinGet troubleshooter
> Automated WinGet troubleshooter

- src/UniGetUI.Core.IconStore/IconDatabase.cs
- src/UniGetUI.Core.LanguageEngine/LanguageEngine.cs
> Attempted fix for #2879

- README.md
-----
Relates to https://github.com/ScoopInstaller/Extras/pull/14311
> doc: update scoop install guide

- README.md
-----
Update the version available for vcpkg in the support table to reflect that it is no longer in prerelease.
> Update vcpkg Support Table

- src/UniGetUI.Core.IconStore/IconCacheEngine.cs
> Fix a typo in the "cached icon is invalid" log

- .github/workflows/winget-prerelease.yml
- .github/workflows/winget-stable.yml
----
I updated the username for the winget workflow to match the current one being used. This should reduce potential future errors.
> Updated username for winget workflow

- src/UniGetUI.Core.Data/CoreData.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Vcpkg.cs
- src/UniGetUI/EntryPoint.cs
- src/UniGetUI/MainWindow.xaml
- src/UniGetUI/MainWindow.xaml.cs
- src/UniGetUI/Pages/MainView.xaml.cs
- src/UniGetUI/Pages/PageInterfaces/IInnerNavigationPage.cs
- src/UniGetUI/Pages/SettingsPages/SettingsBasePage.xaml.cs
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs
> Add Back button to the titlebar

- src/UniGetUI.PackageEngine.Operations/PackageOperations.cs
> Show Version in Update Live Dialog

- src/UniGetUI.PackageEngine.Serializable.Tests/TestSerializablePackage.cs
- src/UniGetUI/MainWindow.xaml
- src/UniGetUI/MainWindow.xaml.cs
- src/UniGetUI/Pages/MainView.xaml.cs
- src/UniGetUI/Pages/PageInterfaces/ISearchBoxPage.cs
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs
- src/UniGetUI/Pages/SoftwarePages/DiscoverSoftwarePage.cs
> Move searchbox to titlebar

- .github/renovate.json
> fix(deps): only use renovate for nuget
