- readme.md
This will have to do for now, as I'm editing this with a massive headache and can't come up with anything else for the time being.
> readme.md: Improve grammar, typography and update the contents

- wingetui/resources/install_scoop.cmd
On a more serious note, and regarding [previous](https://github.com/martinet101/WingetUI/issues/177) [discussions](https://github.com/martinet101/WingetUI/issues/101), some things to keep in mind:
* We want to keep the sentences as effective (i.e., short and clear) and at the same time as grammatically correct as possible – specifically because we're dealing with something being presented in a CLI environment.
* Why do we want to capitalize the first letter of Scoop? There are two things that are important to separate:
#
1. Scoop as a product name.
Notice how every instance is capitalized, as expected.
#
2. Working with Scoop, which is primarily through a CLI;
During operation, the typography is based on operating within a CLI environment, which in this case means only using lower case …
> install_scoop.cmd: Improve grammar

- wingetui/uiSections.py
@martinet101, I believe today you accidentally overwrote this change. By the way, is there any mistake in my code?
Change this 
Into this
> Was this reversion intentional?

- WebBasedData/screenshot-database.json
We have already discussed the format but I'll still post it.
```json
{
"package_count": {
"winget": total_number_of_winget_packages,
"scoop": total_number_of_scoop_packages,
"total": total_number_of_packages_altogether(including all package managers),
"done": currently_done_number_of_packages
},
"winget": 
"package1.id":{
"icon":"icon image linkl(mostly transparent background png icons)",
"images": [
"image link 1",
"image link 2",
]
},
"package2.id":{
"icon":"icon image linkl(mostly transparent background png icons)",
"images": [
"image link 1",
"image link 2",
]
}
"scoop": 
"package1.id":{
"icon":"icon image linkl(mostly transparent background png icons)",
"images": [
"image link 1",
"image link 2",
]
}
}
```
- If a package does not have icons then it has an empty string as value.
- If …
> add the initial 416 packages

- wingetui/uiSections.py
Installed Packages option is "show package info" instead of "show info".  Should I have changed the other way around? I think changing here is better than in Tolgee because other translations would continue different if I changed only the English version there.
> small context menu inconsistency

- wingetui/uiSections.py
> Fix "General preferences" untranslated in other languages

- wingetui/uiSections.py
instead of showing only "Local PC", using f-string allows "Steam" and "MSStore" as well. I'm not sure, though, if it would be better to have a custom message for MSStore
> Fix: Steam and MSStore aren't displayed in error message

- .github/PULL_REQUEST_TEMPLATE.md
use ideas from scoop extras template
-----
> improve pull request template

- wingetui/storeEngine.py
-----
I think you can track without the issue open adding the strings from  https://github.com/marticliment/WingetUI/pull/561/files and https://github.com/marticliment/WingetUI/pull/576/files and https://github.com/marticliment/WingetUI/pull/595/files to Tolgee, right?
-----
Closes #588
> Missing translation

- wingetui/storeEngine.py
- wingetui/uiSections.py
-----
-----
Closes https://github.com/marticliment/WingetUI/issues/566
> Make "Local PC" translatable

- wingetui/customWidgets.py
- wingetui/uiSections.py
Improves responsiveness of discover tab..
Fixes #618
> Discover page optimisations

- wingetui/__init__.py
- wingetui/uiSections.py
Unified translation string for pacakge managers, like:
- Locating {pm}...
- {pm} found: {state}
- {pm} preferences
- {pm} package manager specific preferences
- Enable {pm}
{pm} (package manager) = Winget/Scoop/Chocolatey ...maybe is good write as notice to Toolge
{state} = True/False
More untranslated strings:
- Chocolatey packages are being loaded. Since this is the first time, it might take a while, and they will show here once loaded.
- Blacklist packages
- Show Scoop packages in lowercase
- Local PC
> Unified translation strings for package managers

- wingetui/__init__.py
- wingetui/customWidgets.py
- wingetui/mainWindow.py
Add a welcome page so users can choose with package managers to use
> Startup weapons page

- wingetui/tools.py
CJK characters have different forms in different Chinese variations. The current version uses Microsoft JhengHei UI for all Chinese variations, a font intended to be used in Traditional Chinese. Using Microsoft YaHei UI to display Simplified Chinese characters it's more accurate.
Current
Using MSYH
> Use MS Yahei for Chinese Simplified

- wingetui/storeEngine.py
"Latest" wasn't displayed with the translation in other languages.
Before:
After:
> Use translation for "Latest" in Version combo

- wingetui/wingetHelpers.py
Previously there was a wrong parsing of packages that were installed locally (not from managers), when package name has more than one word. 
Before (take a look at Adobe Flash, Android Studio etc.):
After:
-----
> Fixed winget name/version parsing for installed list

- wingetui/resources/reset_winget_sources.cmd
-----
`reset_winget_sources.cmd` failed to quote paths, causing it to break if WingetUI is installed at a path containing spaces. This PR adds the missing quotes.
-----
Fixes #679
> Fixed WinGet reset script for user profiles with spaces

- scripts/apply_versions.py
os.path.join to join file paths, which is a more robust and platform-independent way to join paths than concatenating strings.
The updated error message is more robust. The original error message did not convert the exception object to a string, so if the exception object did not have a __str__ method defined (which is unlikely but possible), the code would have crashed with a TypeError. By calling str(e), we ensure that we always have a string representation of the error, even if the exception object is not a standard Python exception.
Added checking if file is missing.
> Code Update apply_versions.py

- wingetui/PackageManagers/PackageClasses.py
- wingetui/PackageManagers/choco.py
- wingetui/PackageManagers/npm.py
- wingetui/PackageManagers/pip.py
- wingetui/PackageManagers/sampleHelper.py
- wingetui/PackageManagers/scoop.py
- wingetui/PackageManagers/winget.py
- wingetui/storeEngine.py
- wingetui/uiSections.py
Package managers will declare which capabilities they support, in order for the interface to enable or disable certain elements based on this.
> Add manager capabilities

- readme.md
> add pip, ms store, npm to features

- requirements.txt
Downgrading PyInstaller creates error
-----
-----
Closes #XXXX
> fix unable to build

- wingetui/PackageManagers/winget.py
-----
When trying to update the `RedisInsight` package, the upgrade would fail with:
> Package agreements were not agreed to. Operation cancelled.
I was able to upgrade using winget directly by passing the `--accept-package-agreements` argument, which is already set by WinGetUI for package installations but not updates.
Error log:
```
🟢 Waiting for install permission... title=RedisInsight-v2 2.28.0, id=XP8K1GHCB0F1R2, installId=1690530572.454407
🔵 Given package: <Package: RedisInsight-v2 2.28.0;XP8K1GHCB0F1R2;2.28.0;Winget: msstore;<PackageManagers.winget.WingetPackageManager object at 0x000001AC28D574D0>;<genericCustomWidgets.TreeWidgetItemWithQAction object at 0x000001AC455157C0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdminis …
```
> [PR] Accept package agreements when updating

- wingetui/PackageManagers/npm.py
-----
As suggested in the related issue (#1315), I just replied for the global installed packages the same process done for the local ones.
Now the outdated global installed packages are correctly shown in the panel and updated as well.
---
It solves also the problem of NPM uninstall command.
-----
Closes #1315 
Closes #1320
> [NPM] manage updates for global installed packages and fix uninstall command

- scripts/generate_excel_from_json.py
- wingetui/PackageManagers/choco.py
- wingetui/PackageManagers/scoop.py
- wingetui/__init__.py
- [ x ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [ x ] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [ x ] **Have you tested that the committed code can be executed without errors?**
-----
- Add a `-NoProfile` to every location PowerShell is executed
- Fixes a bug where the listed Scoop updates would include the output of the PowerShell profile
- Also makes it faster as it doesn't have to execute the PowerShell profile before searching for updates
- Added it to the other locations as well, as they are likely …
> Account for cases where the user has a PowerShell profile

- readme.md
readme: Make install through Winget command more specific
When using just "winget install wingetui", Winget complains about
multiple packages carrying similar names and asks the user to be more
specific. Therefore, use the actual package ID in the installation
command.
Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>
The screenshot is in Korean, but it basically shows that Winget finds two packages with "wingetui" in their name and asks you to be more specific.
> readme: Make install through Winget command more specific

- wingetui/Interface/MainWindow.py
Fix window rising to top on chaging theme back.
-----
This change fixes the theme change bug in which the raises itself while fixing its theme when the accent color changes.
I would also try to look into the main theme change issue #1407 in sometime as it requires quiet some trial and error + testing and I am currently not having much time for it. This was a small fix to be made.
Please confirm if it works on Windows 11 (I have tested on Windows 10).
Thanks
-----
Closes #1707
> Fix window rising to top after accent color change

- src/wingetui/PackageEngine/Managers/Chocolatey.cs
As I already had a look at the code via browser I pulled the repo and tested the change. Uninverting the interactive install condition is all that is necessary.
```
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Starting package update operation for package id=k-litecodecpackbasicwith Manager name=Chocolatey
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=True;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Projects\WingetUI\src\wingetui\bin\x64\Debug\net8.0-windows10.0.19041.0\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\ProgramData\chocolatey\bin\choco.exe" upgrade …
```
> #1873 Fix inverted condition for interactive installation of chocolatey packages

- src/wingetui/Interface/SoftwarePages/DiscoverPackages.xaml
- src/wingetui/Interface/SoftwarePages/InstalledPackages.xaml
- src/wingetui/Interface/SoftwarePages/PackageBundle.xaml
- src/wingetui/Interface/SoftwarePages/SoftwareUpdates.xaml
Changes:
Changed rootgrid column widths on SoftwarePages to make the pages populate more of the available space on wider window sizes.
Notes
Not sure about your intent for the look of these pages are but this should change them to keep the same spacing to the edges of the window unless made thinner than the minimum sizes.
Before:
After:
-----
-----
Closes #XXXX
> SoftwarePage width

- readme.md
Fix some random mistakes in the README, mainly typos and grammatical mistakes. Feel free to review the changes
***
ok ☑️
> [Not priority] Fix random mistakes in README (mainly typos)

- src/wingetui/Interface/SoftwarePages/SoftwareUpdates.xaml.cs
Currently, if the user is notified about new available updates via a tray notification, they are given the option to `Update All` or `Open WingetUI`. However, if only a single update is available, these buttons are not shown. This PR removes that distinction, allowing the user to request the upgrade of a single package from the notification without opening the app.
In this case, the `Update All` text is changed to `Update` to reflect the fact that only a single package can be updated.
> Show 'Update' Button in Tray Notification When Only One Update is Available

- src/wingetui/Interface/MainWindow.xaml.cs
Disposes the `TrayIcon` object when the `MainWindow` is closed so that the icon is removed from the taskbar tray.
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing and testing code that does not even compile, breaks other features or does not introduce any useful changes. Thank you for your understanding
-----
Resolves #1995
> Fix #1995: [BUG] Notification tray icon

- src/wingetui/PackageEngine/Managers/Scoop.cs
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing and testing code that does not even compile, breaks other features or does not introduce any useful changes. Thank you for your understanding
-----
Fix automatic repair program not executing correctly when `scoop-search` is not installed
1. `scoop uninstall scoop-search`
2. research in WingetUI
-----
> fix scoop-search autofix error

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding
-----
Changing the Code of Conduct and the Contributing Guidelines to make it have less mistakes.
-----
> Update Code of Conduct, Contributing Guidelines and Security.md

- src/UniGetUI.Core.Data/Licenses.cs
- src/UniGetUI/Interface/Pages/AboutPages/AboutUniGetUI.xaml
- src/UniGetUI/Interface/Pages/AboutPages/AboutUniGetUI.xaml.cs
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding
-----
-----
Closes #XXXX
> Update licenses, disclaimer on the about page

- InstallerExtras/CustomMessages.iss
- WingetUI.iss
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
**Add translation string in the installer ("Install Chocolatey")**
This proposal advocates including multilingual support in the installation process. Currently, the multilingual installer is missing the translation of the "Install Chocolatey" string.
> Add translation string in the installer ("Install Chocolatey")

- src/UniGetUI.Core.Data/CoreData.cs
- src/UniGetUI.Core.Tools/Tools.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers.cs
- src/UniGetUI/EntryPoint.cs
The corresponding encoding will be used for loading WinGet packages and for loading paths with the CoreTools.Which method. Systems that did not support/did had disabled the UTF-8 beta support were experiencing character corruption both in paths and in Packages with non-standard characters
fix #2242 
fix #2239
> Use different encoding code pages depending on the user's locale

- src/UniGetUI.PackageEngine.Managers.WinGet/BundledWinGetLegacyMethods.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers.cs
- src/UniGetUI/Interface/Pages/SettingsPage.xaml.cs
Bundled WinGet is back, to attempt to solve some of the recently shown issues.
Bundled WinGet will be used if
- The default package loading method returns no packages.
- The user specifically enabled bundled WinGet from `UniGetUI Settings` -> `WinGet` -> `Use Legacy bundled WinGet instead of PowerShell CMDLets`
fix #2436 
fix #2414 
fix #2402
fix #2427
fix #2410
> Add back bundled winget compatibility

- src/UniGetUI/Assets/Utilities/scoop_cleanup.cmd
Delete final `cls` so that it's possible to review removal of programs and cache
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding.
-----
Pretty simple: Now the console window will show Scoop's program and cache removal output once complete rather than being hidden.
> Update scoop_cleanup.cmd so that its output can be reviewed

- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/Classes/ManagerLogger.cs
-----
Forgot to fix one warning: [CA1823](https://learn.microsoft.com/pl-pl/dotnet/fundamentals/code-analysis/quality-rules/ca1823)
-----
Relates to https://github.com/marticliment/UniGetUI/pull/2527
> Fix CA1823: Avoid unused private fields

- src/UniGetUI.Core.Data.Tests/CoreTests.cs
- src/UniGetUI.Core.Data/CoreData.cs
- src/UniGetUI.Core.Settings/SettingsEngine.cs
- src/UniGetUI.Interface.Enums/Enums.cs
- src/UniGetUI.PackageEngine.PackageLoader/AbstractPackageLoader.cs
- src/UniGetUI/App.xaml.cs
- src/UniGetUI/EntryPoint.cs
- src/UniGetUI/Interface/MainWindow.xaml.cs
- src/UniGetUI/Interface/Pages/SettingsPage.xaml
- src/UniGetUI/Interface/SoftwarePages/SoftwareUpdatesPage.cs
- src/UniGetUI/PackageEngine/Operations/OperationControl.xaml.cs
- src/UniGetUI/PackageEngine/Operations/PackageOperations.cs
- src/UniGetUI/PackageEngine/Operations/SourceOperations.cs
Needed improvements to the notification system
fix #2649
fix #2332
fix #2061
fix #2192
fix #1443
fix #2356
> Port notifications to the AppSdk api, and fix issues

- .github/workflows/winget-prerelease.yml
-----
I found that the GitHub action did not run with your latest pre-release. After some more digging I found the the prereleased type is a bit misleading. Following this PR change it should actually work now.
-----
> Fixed pre-release workflow

- src/UniGetUI.PackageEngine.Managers.WinGet/Providers/WinGetPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/NativePackageHandler.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/NativeWinGetHelper.cs
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs
- src/UniGetUI/UniGetUI.csproj
Instead of loading the native packages each time they are needed in order to get the details, the icon or the installer options, cache said native package and prevent unneeded calls to the package catalog, drastically reducing CPU usage and icon loading time.
PROS:
- Way faster loading times for details, icons and native installationOptions
- Less CPU impact
- More accurate installationOptions (operation type dependent)
CONS:
- More susceptible to COM Server reset issues
- Potential (but almost insignificant) RAM usage increase
> Add Helper class to cache and load WinGet Native Packages

- src/UniGetUI.Core.Classes.Tests/TaskRecyclerTests.cs
- src/UniGetUI.Core.Classes/SortableObservableCollection.cs
- src/UniGetUI.Core.Classes/TaskRecycler.cs
- src/UniGetUI.Core.Classes/UniGetUI.Core.Classes.csproj
- src/UniGetUI.Core.IconStore/IconCacheEngine.cs
- src/UniGetUI.PackageEngine.Enums/Enums.cs
- src/UniGetUI.PackageEngine.Managers.Cargo/Cargo.cs
- src/UniGetUI.PackageEngine.Managers.Chocolatey/Providers/ChocolateySourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.Generic.NuGet/BaseNuGetDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell/Providers/PowerShellSourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/Providers/PowerShell7SourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Providers/ScoopSourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Scoop.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/Providers/WinGetPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/Providers/WinGetSourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/BundledWinGetHelper.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/IWinGetManagerHelpers.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/NativePackageHandler.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/NativeWinGetHelper.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/BaseProviders/BaseSourceProvider.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/Classes/NullPackageManager.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/PackageManager.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Classes/InstallationOptions.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Package.cs
The `TaskRecycler` class will help prevent calling twice a CPU-intensive method, when the method could be called only once and the result shared with all the callers. This will help reduce CPU usage on methods that are supposed to return the same results when called with little to no time difference. 
An example: The following threads call Manager.GetInstalledPackages, and are likely to do so at the same time.
```csharp
Thread 1:
var installed = Manager.GetInstalledPackages();
Thread 2:
var upgrades = Manager.GetInstalledPackages().where(p => p.IsUpgradable);
```
To optimize this, the following can be done.
```csharp
Thread 1:
var installed = TaskRecycler<IEnumerable<Package>>.RunOrAttachAsync(Manager.GetInstalledPackages);
Thread 2:
var upgrades = …
```
> Create a new TaskRecycler class to cache reusable function calls

- src/UniGetUI.Core.Classes.Tests/TaskRecyclerTests.cs
- src/UniGetUI.Core.Classes/TaskRecycler.cs
- src/UniGetUI.Core.Data/Licenses.cs
- src/UniGetUI.Core.IconEngine.Tests/IconCacheEngineTests.cs
- src/UniGetUI.Core.IconStore/IconCacheEngine.cs
- src/UniGetUI.Core.IconStore/UniGetUI.Core.IconEngine.csproj
- src/UniGetUI.Interface.BackgroundApi/BackgroundApi.cs
- src/UniGetUI.PackageEngine.Managers.Cargo/Cargo.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Scoop.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGetHelpers/NativeWinGetHelper.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Manager/BaseProviders/BaseSourceProvider.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Package.cs
- src/UniGetUI/Pages/SettingsPage.xaml.cs
Improvements to how the icon cache works
- Improve mimetype detection for URLs without extension filename
- This fixes `.ico` files not rendering on Widgets for UniGetUI
- This allows other-than-png files to be added to the icons and screenshots database
- This eases handling of different image formats
- Improvements to the TaskRecycler
- Fix a race condition that would result with a second task being created when another one was already running but hadn't been added to the dictionary
- Resize icons for a smaller impact on disk
- Certain icon formats and sources will be downsized to 256x256
> Improvements to icons

- src/UniGetUI/MainWindow.xaml.cs
- src/UniGetUI/Pages/MainView.xaml.cs
- src/UniGetUI/Pages/SettingsPage.xaml
- src/UniGetUI/Pages/SettingsPage.xaml.cs
-----
This pull request adds a setting to change the default startup page that UniGetUI opens to.
-----
Closes #2733
> Add Setting for Default Startup Page

- src/UniGetUI.PackageEngine.Managers.Vcpkg/Providers/VcpkgPackageDetailsProvider.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Providers/VcpkgSourceProvider.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Vcpkg.cs
-----
This pull request adds the little package information available on the vcpkg database to UniGetUI.
> Add vcpkg Package Details

- src/UniGetUI.Core.Tools.Tests/ToolsTests.cs
- src/UniGetUI.Core.Tools/Tools.cs
-----
This PR changes `CoreTools.FormatAsName` to format multi-word vcpkg options consistently.
Before this PR, vcpkg options with multiple words would have their first word lowercase, and the following words uppercase, but this is inconsistent and looks odd.
> Improve CoreTools.FormatAsName For Multi-Word vcpkg Options

- src/UniGetUI.PackageEngine.Package/Package.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Package.cs
-----
Winget package IDs are normalized to remove the publisher; this pull request does the same thing to vcpkg packages, removing the triplet so they can take advantage of the icons in the screenshot database. It also makes it so the `AbstractPackagesPage` icons take into account this normalization, which it doesn't seem as if it was doing before.
> Fix the vcpkg (normalized) icon ID

- .github/workflows/winget-prerelease.yml
- .github/workflows/winget-stable.yml
-----
This update enhances the WinGet release workflow to ensure it processes only the specific installer file, `UniGetUI.Installer.exe`. It also ensures to use the latest version of the `winget-releaser` since the old v2 release still uses the old Manifest Version 1.5.0, which is not encouraged anymore due to it now being on version 1.9.0; this is happening due to the v2 version of 'winget-releaser` using Komac version 1.11.0, currently we are on Komac version …
> Updated Winget Workflows to Newer Versions

- .github/workflows/update-icons.yaml
> Update update-icons.yaml: Don't run for forks

- src/UniGetUI.PackageEngine.Operations/AbstractOperation.cs
-----
Reorder incorrect / confusing log messages
> Reorder max operation logs

- src/UniGetUI.Core.Data/CoreData.cs
- src/UniGetUI.Core.Tools/Tools.cs
- src/UniGetUI.PackageEngine.Operations/PackageOperations.cs
- src/UniGetUI.PackageEngine.Operations/SourceOperations.cs
- src/UniGetUI.PackageEngine.PackageEngine/PEInterface.cs
- src/UniGetUI.PackageEngine.PackageLoader/AbstractPackageLoader.cs
- src/UniGetUI.PackageEngine.PackageLoader/DiscoverablePackagesLoader.cs
- src/UniGetUI.PackageEngine.PackageLoader/InstalledPackagesLoader.cs
- src/UniGetUI.PackageEngine.PackageLoader/PackageBundlesLoader.cs
- src/UniGetUI.PackageEngine.PackageLoader/UpgradablePackagesLoader.cs
- src/UniGetUI/App.xaml.cs
- src/UniGetUI/Pages/SettingsPage.xaml
- test_publish.cmd
- Redirect WinGet temp folder when running elevated, so it does not change ACLs on `%temp%\WinGet`, and then it stops working due to incorrect permissions. This would only happen when UniGetUI was running from a local account, and different credentials of a different account were provided to Elevator/GSudo.
- Wait for an internet connection before loading package lists. This condition also triggered the WinGet corruption banner.
> Fix WinGet getting corrupted on devices with non-admin accounts

- src/UniGetUI/Pages/DialogPages/DesktopShortcuts.xaml
- src/UniGetUI/Pages/DialogPages/DesktopShortcuts.xaml.cs
- src/UniGetUI/Pages/DialogPages/DialogHelper_Generic.cs
> Allow Manual Scanning of Desktop Shortcuts

- src/UniGetUI/Pages/MainView.xaml.cs
-----
Use `KeyDown` event for handling MainView keyboard shortcuts to prevent handling key presses initiated in other applications. Ignoring events with `KeyStatus.WasKeyDown == true` to ignore key down events resulting from holding down a key.
-----
Closes #3298
> Use KeyDown instead of KeyUp to handle MainView keyboard shortcuts

- src/UniGetUI.PackageEngine.Managers.Vcpkg/Vcpkg.cs
- src/UniGetUI/Pages/SettingsPage.xaml.cs
-----
In attempting to update `bzip2` before pressing "update now" to the new 3.1.7 update, the bzip update fails (not due to UniGetUI, but due to vcpkg that was _impacted_ by UniGetUI), and as microsoft/vcpkg#43297 suggests it's because a recent vcpkg commit changed the way the system works, however while commit 9e3482c307cb549692cf3938af7adf9f70c341db in #3278 bootstraps vcpkg upon UniGetUI opening (giving it the new version with the updated code), it doesn't …
> Always Update Indexes

- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Package.cs
-----
Steam icon IDs, with `:` in the name, are invalid filepaths (for the icon directory).
I SWEAR I tested #3347, I just didn't see the error in the logs 😭.
> Fix Steam Icons Having An Invalid Path

- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml
- src/UniGetUI/Pages/SoftwarePages/AbstractPackagesPage.xaml.cs
-----
I noticed that #3354 does not fully fix #3298 as the package list still uses KeyUp to handle keyboard shortcuts. Moved the key press handling to PreviewKeyDown to fix this.
-----
Relates to #3298
> Use PreviewKeyDown instead of KeyUp to handle package list keyboard shortcuts

- src/UniGetUI.PackageEngine.Managers.Scoop/Scoop.cs
-----
Changes:
- Updated the URL for the official Scoop nirsoft to ScoopInstaller/Nirsoft to reflect the change made to the official buckets in Scoop commit [ad0f6178d05192497c07aef55d4f3aff7516b982](https://github.com/ScoopInstaller/Scoop/commit/ad0f6178d05192497c07aef55d4f3aff7516b982)
> Update Scoop nirsoft bucket URL to ScoopInstaller/Nirsoft

- src/UniGetUI.PackageEngine.Managers.Cargo/Helpers/CargoPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Chocolatey/Helpers/ChocolateyPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Dotnet/Helpers/DotNetPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Npm/Helpers/NpmPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Pip/Helpers/PipPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell/Helpers/PowerShellPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/Helpers/PowerShell7PkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Helpers/ScoopPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Helpers/VcpkgPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/Helpers/WinGetPkgOperationHelper.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Classes/InstallOptionsFactory.cs
- src/UniGetUI.PackageEngine.Serializable.Tests/TestInstallOptions.cs
- src/UniGetUI.PackageEngine.Serializable.Tests/TestSerializableBundle.cs
- src/UniGetUI.PackageEngine.Serializable.Tests/TestSerializablePackage.cs
- src/UniGetUI.PackageEngine.Serializable/InstallOptions.cs
- src/UniGetUI/Controls/MenuForPackage.cs
- src/UniGetUI/Pages/DialogPages/InstallOptions_Manager.xaml
- src/UniGetUI/Pages/DialogPages/InstallOptions_Manager.xaml.cs
- src/UniGetUI/Pages/DialogPages/InstallOptions_Package.xaml
- src/UniGetUI/Pages/DialogPages/InstallOptions_Package.xaml.cs
Install, update and uninstall custom CLI arguments will be different.
fix #3526
> Separe Install, update and uninstall custom command-line args

- src/UniGetUI.Interface.Enums/Enums.cs
- src/UniGetUI/Pages/DialogPages/DialogHelper_Packages.cs
- src/UniGetUI/Pages/SettingsPages/GeneralPages/Administrator.xaml
- src/UniGetUI/Pages/SoftwarePages/PackageBundlesPage.cs
Display a report and warn the user when an imported package bundle contains potentially unsafe install options.
Each affected package, and the settings that triggered the alert will be displayed
> Warn the user when a bundle contains potentially harmful prefs

- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Package.cs
-----
To improve clarity for future readers of this complicated string truncation, the comments have been relocated to more obviously show what segments they are detailing and why each line does what it does for Microsoft Store icons.
> Improve local icon detection code comments

- src/UniGetUI.PackageEngine.Enums/ManagerCapabilities.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/PowerShell7.cs
- src/UniGetUI.PackageEngine.Operations/PackageOperations.cs
- src/UniGetUI.PackageEngine.Serializable/InstallOptions.cs
- src/UniGetUI/Pages/DialogPages/InstallOptions_Manager.xaml
- src/UniGetUI/Pages/DialogPages/InstallOptions_Manager.xaml.cs
- src/UniGetUI/Pages/DialogPages/InstallOptions_Package.xaml
- src/UniGetUI/Pages/DialogPages/InstallOptions_Package.xaml.cs
Clear older versions of PowerShell7 modules on update. This option can be enabled per-package or on a powershell7-level basis (for all the packages)
fix #3123
fix #3342
> Clear older versions of PowerShell7 modules on update

- src/UniGetUI.PAckageEngine.Interfaces/IPackageDetails.cs
- src/UniGetUI.PackageEngine.Enums/ManagerCapabilities.cs
- src/UniGetUI.PackageEngine.Managers.Chocolatey/Chocolatey.cs
- src/UniGetUI.PackageEngine.Managers.Dotnet/DotNet.cs
- src/UniGetUI.PackageEngine.Managers.Generic.NuGet/BaseNuGet.cs
- src/UniGetUI.PackageEngine.Managers.Generic.NuGet/BaseNuGetDetailsHelper.cs
- src/UniGetUI.PackageEngine.Managers.Npm/Helpers/NpmPkgDetailsHelper.cs
- src/UniGetUI.PackageEngine.Managers.Npm/Npm.cs
- src/UniGetUI.PackageEngine.Managers.Pip/Helpers/PipPkgDetailsHelper.cs
- src/UniGetUI.PackageEngine.Managers.Pip/Pip.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell/PowerShell.cs
- src/UniGetUI.PackageEngine.Managers.PowerShell7/PowerShell7.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Helpers/ScoopPkgDetailsHelper.cs
- src/UniGetUI.PackageEngine.Managers.Scoop/Scoop.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Helpers/VcpkgPkgDetailsHelper.cs
- src/UniGetUI.PackageEngine.Managers.Vcpkg/Vcpkg.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/ClientHelpers/BundledWinGetHelper.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/ClientHelpers/NativeWinGetHelper.cs
- src/UniGetUI.PackageEngine.Managers.WinGet/WinGet.cs
- src/UniGetUI.PackageEngine.PackageManagerClasses/Packages/Classes/PackageDetails.cs
- src/UniGetUI/Pages/DialogPages/PackageDetailsPage.xaml
- src/UniGetUI/Pages/DialogPages/PackageDetailsPage.xaml.cs
Add a `Dependencies` field on Package Details
fix #602
fix #1306
> Add dependencies field to Package Details

- src/UniGetUI.Core.Tools/SerializationHelpers.cs
- src/UniGetUI.PackageEngine.Serializable/InstallOptions.cs
- src/UniGetUI.PackageEngine.Serializable/SerializableBundle.cs
- src/UniGetUI.PackageEngine.Serializable/SerializableComponent.cs
- src/UniGetUI.PackageEngine.Serializable/SerializableIncompatiblePackage.cs
- src/UniGetUI.PackageEngine.Serializable/SerializablePackage.cs
- src/UniGetUI.PackageEngine.Serializable/SerializableUpdatesOptions.cs
- src/UniGetUI/Pages/SoftwarePages/PackageBundlesPage.cs
- src/UniGetUI/Services/GitHubBackupService.cs
Improvements to bundle save file size. So far, ~300K -> ~100K
> Bundles file size improvements
